name: SPARQL Unicorn Ontology Documentation CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"  
  build:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    with: 
        rdffilepath: data/navisone_maritime_thesaurus.ttl
        docpath: docs
        prefixns: http://data.archaeology.link/data/maritimethesaurus/
        prefixnsshort: nomt
        indexpages: true
        createcollections: true
        preferredlang: en
        ghpages: true
        templatedir: https://github.com/ogham-lod/sparqlunicornGoesGIS-ontdoc-template/archive/refs/tags/v0.1.zip
